apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    database: "[quickfaqs-]YYYY.MM.DD"
    url: http://elasticsearch:9200
    jsonData:
      timeField: "@timestamp"
      esVersion: 7.0.0
      interval: Daily
      logMessageField: message
      logLevelField: level
